config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :committees
  resources :voivodeships
  resources :votes
  resources :constituencies

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/committee.rb
class Committee < ActiveRecord::Base
	has_many :votes
	has_many :constituencies
	has_and_belongs_to_many :voivodeships, :join_table => :committees_voivodeships


end

app/models/committees_voivodeship.rb
class CommitteesVoivodeship < ActiveRecord::Base
	belongs_to :committe
	belongs_to :voivodeship
end

app/models/constituency.rb
class Constituency < ActiveRecord::Base
	has_many :votes
	belongs_to :voivodeship
	# belongs_to :constituency
end

app/models/voivodeship.rb
class Voivodeship < ActiveRecord::Base
	has_and_belongs_to_many :committees, :join_table => :committees_voivodeships
	has_many :constituencies
	accepts_nested_attributes_for :constituencies, :allow_destroy => true
#	has_many :votes, through: :constituencies

	

end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :committee
	belongs_to :constituency
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController

	def index
		@committees = Committee.all
	end

	def show
    @committee = Committee.find(params[:id])
	end

  def edit
    @committee = Committee.find(params[:id])
  end

	def new
    @committee = Committee.new
  end

  def create
   	@committee = Committee.new(committee_params)

    if @committee.save
      redirect_to committees_path, notice: "Dodałeś komitet wyborczy"
    else
      render new_committee_path
    end  
  end

  def update
    @committee = Committee.find(params[:id])
    respond_to do |format|
      if @committee.update(committee_params)
        format.html { redirect_to @committee, notice: 'Committee was successfully updated.' }
        format.json { render :show, status: :ok, location: @committee }
      else
        format.html { render :edit }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @committee = Committee.find(params[:id])
    @committee.destroy
    respond_to do |format|
      format.html { redirect_to committees_url, notice: 'Komitet został usunięty' }
      format.json { head :no_content }
    end
  end

  private
  def committee_params
    params.require(:committee).permit(
        :name,
        :image_file_name
        
    )
  end  
end

app/controllers/constituencies_controller.rb
class ConstituenciesController < ApplicationController
  before_action :set_constituency, only: [:show, :edit, :update, :destroy]

  # GET /constituencies
  # GET /constituencies.json
  def index
    @constituencies = Constituency.all
  end

  # GET /constituencies/1
  # GET /constituencies/1.json
  def show
  end

  # GET /constituencies/new
  def new
    @constituency = Constituency.new
  end

  # GET /constituencies/1/edit
  def edit
  end

  # POST /constituencies
  # POST /constituencies.json
  def create
    @constituency = Constituency.new(constituency_params)

    respond_to do |format|
      if @constituency.save
        format.html { redirect_to @constituency, notice: 'Constituency was successfully created.' }
        format.json { render :show, status: :created, location: @constituency }
      else
        format.html { render :new }
        format.json { render json: @constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /constituencies/1
  # PATCH/PUT /constituencies/1.json
  def update
    respond_to do |format|
      if @constituency.update(constituency_params)
        format.html { redirect_to @constituency, notice: 'Constituency was successfully updated.' }
        format.json { render :show, status: :ok, location: @constituency }
      else
        format.html { render :edit }
        format.json { render json: @constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /constituencies/1
  # DELETE /constituencies/1.json
  def destroy
    @constituency.destroy
    respond_to do |format|
      format.html { redirect_to constituencies_url, notice: 'Constituency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_constituency
      @constituency = Constituency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def constituency_params
      params.require(:constituency).permit(:name, :voters, :used_ballots, :invalid_no_chose, :invalid_more_choises, :invalid_other, :voivodeship_id)
    end
end

app/controllers/voivodeships_controller.rb
class VoivodeshipsController < ApplicationController
	
	 # GET /voivodeships
	def index
		@voivodeships = Voivodeship.all
	end

	# GET /voivodeships/1
	def show
    @voivodeship = Voivodeship.find(params[:id])
	end

	# GET /voivodeships/1/edit
	def edit
    @voivodeship = Voivodeship.find(params[:id])
	end

  def new
    @voivodeship = Voivodeship.new
  end

	# POST /voivodeships
  def create
   	@voivodeship = Voivodeship.new(voivodeship_params)

    if @voivodeship.save
      redirect_to voivodeships_path, notice: "Dodałeś wojewodztwo"
    else
      render new_voivodeship_path
    end  
  end

  def update
    @voivodeship = Voivodeship.find(params[:id])
    respond_to do |format|
      if @voivodeship.update(voivodeship_params)
        format.html { redirect_to @voivodeship, notice: 'Voivodeship was successfully updated.' }
        format.json { render :show, status: :ok, location: @voivodeship }
      else
        format.html { render :edit }
        format.json { render json: @voivodeship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voivodeships/1
  def destroy
    @voivodeship = Voivodeship.find(params[:id])
    @voivodeship.destroy
    respond_to do |format|
      format.html { redirect_to voivodeships_url, notice: 'Voivodeship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def voivodeship_params
    params.require(:voivodeship).permit(:id, :name, :electoral_mandates)  
  end 



end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	def index

	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/helpers/constituencies_helper.rb
module ConstituenciesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/voivodeships_helper.rb
module VoivodeshipsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/committees/_form.html.erb
<%= form_for(@committee) do |f| %>
  <% if @committee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@committee.errors.count, "error") %> prohibited this committee from being saved:</h2>

      <ul>
      <% @committee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "logo" %><br>
    <%= f.text_field :image_file_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/committees/edit.html.erb
<h1>Editing Committee</h1>

<%= render 'form' %>

<%= link_to 'Show', @committee %> |
<%= link_to 'Back', committees_path %>

app/views/committees/index.html.erb
<p id="notice"><%= notice %></p>

<h1> Lista komitetów </h1>

<table>
	<thead>
		<tr>
			<th> Nazwa komitetu </th>
			<th colspan = "3"></th>
		</tr>
	</thead>

	<tbody>
		<% @committees.each do |committee| %>
		<tr>
			<td><%= committee.name %></td>
			<td><%=link_to 'Pokaż', committee %></td>
			<td><%=link_to 'Edytuj', edit_committee_path(committee)%></td>
			<td><%=link_to 'Usuń', committee, method: :delete, data: {confirm: "Czy jesteś pewien?"} %></td>
		</tr>
		<%end %>
	</tbody>
</table>
<br>

<%= link_to 'Dodaj komitet', new_committee_path %>

app/views/committees/new.html.erb
<h1>New Committee</h1>

<%= render 'form' %>

<%= link_to 'Back', committees_path %>

app/views/committees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @committee.name %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @committee.image_file_name %>
</p>

<%= link_to 'Edit', edit_committee_path(@committee) %> |
<%= link_to 'Back', committees_path %>

app/views/constituencies/_form.html.erb
<%= form_for(@constituency) do |f| %>
  <% if @constituency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@constituency.errors.count, "error") %> prohibited this constituency from being saved:</h2>

      <ul>
      <% @constituency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class ="form-group">
    <%= f.label :Województwo %>
    <%= f.select :voivodeship_id,
        Voivodeship.all.collect { |x| [x.name, x.id]},
        {:include_blank => 'Wybierz województwo'},
        class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :voters %><br>
    <%= f.number_field :voters %>
  </div>
  <div class="field">
    <%= f.label :used_ballots %><br>
    <%= f.number_field :used_ballots %>
  </div>
  <div class="field">
    <%= f.label :invalid_no_chose %><br>
    <%= f.number_field :invalid_no_chose %>
  </div>
  <div class="field">
    <%= f.label :invalid_more_choises %><br>
    <%= f.number_field :invalid_more_choises %>
  </div>
  <div class="field">
    <%= f.label :invalid_other %><br>
    <%= f.number_field :invalid_other %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/constituencies/edit.html.erb
<h1>Editing Constituency</h1>

<%= render 'form' %>

<%= link_to 'Show', @constituency %> |
<%= link_to 'Back', constituencies_path %>

app/views/constituencies/index.html.erb
<h1> Okręgi wyborcze </h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Województwo</th>
      <th>Voters</th>
      <th>Used ballots</th>
      <th>Invalid no chose</th>
      <th>Invalid more choises</th>
      <th>Invalid other</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @constituencies.each do |constituency| %>
      <tr>
        <td><%= constituency.name %></td>
        <td><%= constituency.voivodeship %></td>
        <td><%= constituency.voters %></td>
        <td><%= constituency.used_ballots %></td>
        <td><%= constituency.invalid_no_chose %></td>
        <td><%= constituency.invalid_more_choises %></td>
        <td><%= constituency.invalid_other %></td>
        <td><%= link_to 'Show', constituency %></td>
        <td><%= link_to 'Edit', edit_constituency_path(constituency) %></td>
        <td><%= link_to 'Destroy', constituency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj okręg', new_constituency_path %>

app/views/constituencies/new.html.erb
<h1>Nowy okręg</h1>

<%= render 'form' %>

<%= link_to 'Wróć', constituencies_path %>

app/views/constituencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @constituency.name %>
</p>

<p>
  <strong>Voters:</strong>
  <%= @constituency.voters %>
</p>

<p>
  <strong>Used ballots:</strong>
  <%= @constituency.used_ballots %>
</p>

<p>
  <strong>Invalid no chose:</strong>
  <%= @constituency.invalid_no_chose %>
</p>

<p>
  <strong>Invalid more choises:</strong>
  <%= @constituency.invalid_more_choises %>
</p>

<p>
  <strong>Invalid other:</strong>
  <%= @constituency.invalid_other %>
</p>

<%= link_to 'Edit', edit_constituency_path(@constituency) %> |
<%= link_to 'Back', constituencies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PkwProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/voivodeships/_form.html.erb
<%= form_for(@voivodeship) do |f| %>
  <% if @voivodeship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voivodeship.errors.count, "error") %> prohibited this voivodeship from being saved:</h2>

      <ul>
      <% @voivodeship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "nazwa" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "liczba manadatów" %><br>
    <%= f.number_field :electoral_mandates %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/voivodeships/edit.html.erb
<h1>Editing Voivodeship</h1>

<%= render 'form' %>

<%= link_to 'Show', @voivodeship %> |
<%= link_to 'Back', voivodeships_path %>

app/views/voivodeships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista województw</h1>

<table>
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Liczba mandatów</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voivodeships.each do |voivodeship| %>
      <tr>
        <td><%= voivodeship.name %></td>
        <td><%= voivodeship.electoral_mandates %></td>
        <td><%= link_to 'Pokaż', voivodeship %></td>
        <td><%= link_to 'Edytuj', edit_voivodeship_path(voivodeship) %></td>
        <td><%= link_to 'Usuń', voivodeship, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj województwo', new_voivodeship_path %>

app/views/voivodeships/new.html.erb
<h1>Nowe województwo</h1>

<%= render 'form' %>

<%= link_to 'Wróć', voivodeships_path %>

app/views/voivodeships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nazwa:</strong>
  <%= @voivodeship.name %>
</p>

<p>
  <strong>Liczba mandatów:</strong>
  <%= @voivodeship.electoral_mandates %>
</p>

<%= link_to 'Edytuj', edit_voivodeship_path(@voivodeship) %> |
<%= link_to 'Wróc', voivodeships_path %>

app/views/votes/index.html.erb
<h1> Głosy <h1>